import pandas as pd
import matplotlib.pyplot as plt
import os

# Load the compression results datasets
low_path = "../compression_results_low_26.csv"
high_path = "../compression_results_high_26.csv"

df_low = pd.read_csv(low_path)
df_high = pd.read_csv(high_path)

# Add a column to distinguish between datasets
df_low["Repetitiveness"] = "Low Repetitiveness"
df_high["Repetitiveness"] = "High Repetitiveness"

# Combine the two dataframes
df = pd.concat([df_low, df_high])

# Create figure with two subplots side by side for presentation
fig, axes = plt.subplots(1, 2, figsize=(16, 6), sharey=False)

# Calculate statistics for mean and standard deviation
stats = df.groupby(["p_value", "Repetitiveness"]).agg(
    mean_nodes=("num_new_nodes", "mean"),
    std_nodes=("num_new_nodes", "std"),
    mean_trans=("num_new_transitions", "mean"),
    std_trans=("num_new_transitions", "std")
).reset_index()

# --- First Graph: Number of New Nodes Comparison ---
for rep in ["Low Repetitiveness", "High Repetitiveness"]:
    sub = stats[stats["Repetitiveness"] == rep]
    axes[0].errorbar(sub["p_value"], sub["mean_nodes"], yerr=sub["std_nodes"], 
                     label=rep, marker="o", capsize=5, linewidth=2, markersize=8)

axes[0].set_title("Number of Nodes from Trie Compression\nby Repetitiveness Level", fontsize=18, pad=20)
axes[0].set_xlabel("p", fontsize=18)
axes[0].set_ylabel("Number of Nodes", fontsize=18)
axes[0].legend(loc='upper right', fontsize=16)
axes[0].grid(True, alpha=0.3)
axes[0].tick_params(axis='both', which='major', labelsize=12)

# --- Second Graph: Number of New Transitions Comparison ---
for rep in ["Low Repetitiveness", "High Repetitiveness"]:
    sub = stats[stats["Repetitiveness"] == rep]
    axes[1].errorbar(sub["p_value"], sub["mean_trans"], yerr=sub["std_trans"], 
                     label=rep, marker="o", capsize=5, linewidth=2, markersize=8)

axes[1].set_title("Number of Transitions from Trie Compression\nby Repetitiveness Level", fontsize=18, pad=20)
axes[1].set_xlabel("p", fontsize=18)
axes[1].set_ylabel("Number of Transitions", fontsize=18)
axes[1].legend(loc='upper right', fontsize=16)
axes[1].grid(True, alpha=0.3)
axes[1].tick_params(axis='both', which='major', labelsize=12)

# Remove automatic title generated by pandas and improve layout
plt.suptitle('')  # Remove any default suptitle
plt.tight_layout()

# Create output directory if it doesn't exist
output_dir = "output_plots"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Save the plots in multiple formats
plot_filename = "high_low_comparison"
formats = ['png', 'pdf', 'svg']

for fmt in formats:
    filepath = os.path.join(output_dir, f"{plot_filename}.{fmt}")
    plt.savefig(filepath, format=fmt, dpi=300, bbox_inches='tight')
    print(f"Plot saved as: {filepath}")

# Display the plot
# plt.show()